### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by allrude** [timoffmax/magento2_topbar#1]
Hi I installed the module on a clean M2.3 install but it doesn't work, i see it on the backend but not the frontend

**Comment by timoffmax** [comment]
> Hi I installed the module on a clean M2.3 install but it doesn't work, i see it on the backend but not the frontend

Hi @allrude ! Sorry, but I can't reproduce your problem. I've used clean Magento 2.3.0 CE installation (it had been downloaded from official Magento site) and PHP 7.2.14.
Did you enable the module in **Stores -> Settings -> Configuration -> Timoffmax -> Top Information Bar**?
I've added some clarification in README.md, please take a look.

Let me know if you still have questions.

**Comment by timoffmax** [comment]
I close it because I can't reproduce the problem and don't get any response for a long time.
